name: Build and deploy Node.js app to Azure Web App - kuhologger-client

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        # This ensures the build runs in the root directory
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # We upload the entire root so the 'dist' folder is included
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: azure/webapps-deploy@v3 # Using the deploy action directly to handle artifacts
        with:
          app-name: 'kuhologger-client'
          slot-name: 'Production'
          package: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_44D2B2E2F8E64F4585EB7C48E03246E3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_36897F40623C49709AA914085137DD57 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_61386C92FFA14096859735D1401256CF }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kuhologger-client'
          slot-name: 'Production'
          package: .
